### PR TITLE
Changed Scope Reference for CHANNEL_MANAGE_CHAT_SETTINGS

### PR DESCRIPTION
**Pull request by gitagogaming**
Went to change chat settings and the scope details set was incorrect.
For quick reference - https://dev.twitch.tv/docs/api/reference#update-chat-settings

### CODE REVIEW

**Comment by Teekeks** [comment]
in that case the name should also be changed to reflect the scope name

**Comment by gitagogaming** [comment]
done - totally overlooked that

**Comment by Teekeks** [comment]
this should also changed in update_chat_settings

**Comment by gitagogaming** [comment]
... Learning lessons right there for me.. make sure  to look into other files where its referenced

 Thanks Teeks :)

**Comment by Teekeks** [comment]
One final thing: make sure to also change the docstring :D

**Pull request merged**
